'use strict';

const { ethers }    = require('ethers');
const { pool }      = require('../config/database');
const { getSigner, contractAddresses } = require('../config/blockchain');
const logger        = require('../utils/logger')('multiPartyEscrowService');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a UUID string to a 32-byte hex value matching uuidToBytes32 used elsewhere.
 * @param {string} uuid e.g. "550e8400-e29b-41d4-a716-446655440000"
 * @returns {string} "0x<64 hex chars>"
 */
const uuidToBytes32 = (uuid) =>
    ethers.zeroPadValue('0x' + uuid.replace(/-/g, ''), 32);

/**
 * Lazily resolve the deployed MultiPartyEscrow contract.
 * Falls back to the MULTI_PARTY_ESCROW_ADDRESS env variable when the
 * deployed artifacts haven't been generated yet (dev / CI environments).
 */
const getContract = async () => {
    const signer  = await getSigner();
    const address =
        (contractAddresses.multiPartyEscrow) ||
        process.env.MULTI_PARTY_ESCROW_ADDRESS;

    if (!address) {
        throw new Error(
            'MultiPartyEscrow contract address is not configured. ' +
            'Set contractAddresses.multiPartyEscrow or MULTI_PARTY_ESCROW_ADDRESS.'
        );
    }

    // ABI is generated by Hardhat after compilation; tolerate missing file in dev.
    let abi;
    try {
        abi = require('../../artifacts/contracts/MultiPartyEscrow.sol/MultiPartyEscrow.json').abi;
    } catch {
        logger.warn('MultiPartyEscrow artifact not found – blockchain calls will fail until compiled.');
        abi = [];
    }

    return new ethers.Contract(address, abi, signer);
};

// ---------------------------------------------------------------------------
// Service functions
// ---------------------------------------------------------------------------

/**
 * Create a multi-party escrow record in the database (off-chain).
 * The escrow is in 'draft' status until activated on-chain via activateOnChain().
 *
 * @param {object} opts
 * @param {string}  opts.invoiceId       UUID of the linked invoice (nullable)
 * @param {string}  opts.title           Human-readable escrow title
 * @param {string}  [opts.description]
 * @param {number}  opts.totalAmount     Decimal amount (e.g. 1000.00)
 * @param {string}  [opts.currency]      Default: 'USDC'
 * @param {string}  [opts.tokenAddress]  ERC-20 contract address (null = ETH)
 * @param {number}  [opts.durationSeconds]
 * @param {Array<{walletAddress:string, role:string, userId?:string}>} opts.participants
 * @param {Array<{title:string, description?:string, amount:number, requiredApprovals?:number, metadata?:object}>} opts.milestones
 * @param {string}  opts.createdByUserId UUID of the creating user
 * @returns {object} The created multi_party_escrows row (with escrow_id)
 */
const createEscrow = async ({
    invoiceId,
    title,
    description,
    totalAmount,
    currency = 'USDC',
    tokenAddress = null,
    durationSeconds = 0,
    participants = [],
    milestones = [],
    createdByUserId,
}) => {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        // 1. Insert escrow header
        const escrowRes = await client.query(
            `INSERT INTO multi_party_escrows
                 (invoice_id, title, description, total_amount, currency,
                  token_address, status, created_by, expires_at)
             VALUES ($1, $2, $3, $4, $5, $6, 'draft', $7,
                     CASE WHEN $8::int > 0
                          THEN NOW() + ($8 || ' seconds')::INTERVAL
                          ELSE NULL END)
             RETURNING *`,
            [
                invoiceId || null,
                title,
                description || null,
                totalAmount,
                currency,
                tokenAddress,
                createdByUserId,
                durationSeconds,
            ]
        );
        const escrow = escrowRes.rows[0];

        // 2. Insert participants
        for (const p of participants) {
            await client.query(
                `INSERT INTO escrow_participants
                     (escrow_id, user_id, wallet_address, role)
                 VALUES ($1, $2, $3, $4)
                 ON CONFLICT (escrow_id, wallet_address) DO NOTHING`,
                [escrow.escrow_id, p.userId || null, p.walletAddress, p.role]
            );
        }

        // 3. Insert milestones
        for (let i = 0; i < milestones.length; i++) {
            const m = milestones[i];
            await client.query(
                `INSERT INTO escrow_milestones
                     (escrow_id, title, description, amount,
                      required_approvals, order_index, metadata)
                 VALUES ($1, $2, $3, $4, $5, $6, $7)`,
                [
                    escrow.escrow_id,
                    m.title,
                    m.description || null,
                    m.amount,
                    m.requiredApprovals || 1,
                    i,
                    JSON.stringify(m.metadata || {}),
                ]
            );
        }

        await client.query('COMMIT');
        logger.info(`MultiPartyEscrow created: ${escrow.escrow_id}`);
        return escrow;
    } catch (err) {
        await client.query('ROLLBACK');
        throw err;
    } finally {
        client.release();
    }
};

/**
 * Publish the escrow and its milestones to the blockchain.
 * Updates the DB record to status='active' once the TX is confirmed.
 *
 * @param {string} escrowId UUID of the record in multi_party_escrows
 * @param {string} [tokenAddress]   Override token address (uses DB value by default)
 * @param {number} [durationSeconds] Override duration
 * @returns {ethers.TransactionReceipt}
 */
const activateOnChain = async (escrowId, tokenAddress, durationSeconds) => {
    // Load full escrow data
    const { rows } = await pool.query(
        `SELECT e.*,
                COALESCE(
                    json_agg(DISTINCT jsonb_build_object(
                        'wallet_address', p.wallet_address, 'role', p.role
                    )) FILTER (WHERE p.id IS NOT NULL),
                    '[]'::json
                ) AS participants,
                COALESCE(
                    json_agg(
                        jsonb_build_object(
                            'title',              m.title,
                            'description',        m.description,
                            'amount',             m.amount,
                            'required_approvals', m.required_approvals,
                            'order_index',        m.order_index
                        ) ORDER BY m.order_index
                    ) FILTER (WHERE m.id IS NOT NULL),
                    '[]'::json
                ) AS milestones
         FROM   multi_party_escrows e
         LEFT   JOIN escrow_participants p ON p.escrow_id = e.escrow_id
         LEFT   JOIN escrow_milestones   m ON m.escrow_id = e.escrow_id
         WHERE  e.escrow_id = $1
         GROUP  BY e.id`,
        [escrowId]
    );

    if (!rows.length) throw new Error(`Escrow not found: ${escrowId}`);
    const escrow = rows[0];

    const contract  = await getContract();
    const bytes32Id = uuidToBytes32(escrowId);
    const token     = tokenAddress || escrow.token_address || ethers.ZeroAddress;
    const amount    = ethers.parseUnits(String(escrow.total_amount), 6); // USDC has 6 dp
    const duration  = durationSeconds != null ? durationSeconds
        : escrow.expires_at ? Math.max(0, Math.floor((new Date(escrow.expires_at) - Date.now()) / 1000))
        : 0;

    const wallets = escrow.participants.map((p) => p.wallet_address);
    const roles   = escrow.participants.map((p) => p.role);

    // Register escrow on-chain
    const createTx      = await contract.createEscrow(bytes32Id, token, amount, duration, wallets, roles);
    const createReceipt = await createTx.wait();

    // Publish milestones on-chain
    for (const m of escrow.milestones) {
        const milestoneAmount = ethers.parseUnits(String(m.amount), 6);
        const mTx = await contract.createMilestone(
            bytes32Id,
            m.title,
            m.description || '',
            milestoneAmount,
            m.required_approvals
        );
        await mTx.wait();
    }

    // Update DB status
    await pool.query(
        `UPDATE multi_party_escrows
         SET    status = 'active', on_chain_tx_hash = $1, updated_at = NOW()
         WHERE  escrow_id = $2`,
        [createReceipt.hash, escrowId]
    );

    logger.info(`MultiPartyEscrow activated on-chain: ${escrowId} tx=${createReceipt.hash}`);
    return createReceipt;
};

/**
 * Add a single participant to an existing escrow (DB + optionally on-chain).
 *
 * @param {string} escrowId
 * @param {{walletAddress:string, role:string, userId?:string, onChain?:boolean}} opts
 * @returns {object} The inserted/updated escrow_participants row
 */
const addParticipant = async (escrowId, { walletAddress, role, userId = null, onChain = false }) => {
    // Validate escrow exists and is active
    const { rows } = await pool.query(
        'SELECT status FROM multi_party_escrows WHERE escrow_id = $1',
        [escrowId]
    );
    if (!rows.length) throw new Error(`Escrow not found: ${escrowId}`);
    if (rows[0].status !== 'active' && rows[0].status !== 'draft') {
        throw new Error('Cannot add participants to a non-active escrow');
    }

    const result = await pool.query(
        `INSERT INTO escrow_participants (escrow_id, user_id, wallet_address, role)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (escrow_id, wallet_address)
             DO UPDATE SET role = EXCLUDED.role, is_active = TRUE, user_id = COALESCE(EXCLUDED.user_id, escrow_participants.user_id)
         RETURNING *`,
        [escrowId, userId, walletAddress, role]
    );

    if (onChain && rows[0].status === 'active') {
        const contract  = await getContract();
        const bytes32Id = uuidToBytes32(escrowId);
        const tx        = await contract.addParticipant(bytes32Id, walletAddress, role);
        await tx.wait();
    }

    return result.rows[0];
};

/**
 * Create a new milestone on an existing escrow (DB only; on-chain via activateOnChain or explicit call).
 *
 * @param {string} escrowId
 * @param {{title:string, description?:string, amount:number, requiredApprovals?:number, metadata?:object, onChain?:boolean}} opts
 * @returns {object} The inserted escrow_milestones row
 */
const createMilestone = async (escrowId, {
    title,
    description = null,
    amount,
    requiredApprovals = 1,
    metadata = {},
    onChain = false,
}) => {
    const orderRes  = await pool.query(
        'SELECT COALESCE(MAX(order_index), -1) + 1 AS next_idx FROM escrow_milestones WHERE escrow_id = $1',
        [escrowId]
    );
    const nextIndex = orderRes.rows[0].next_idx;

    const result = await pool.query(
        `INSERT INTO escrow_milestones
             (escrow_id, title, description, amount, required_approvals, order_index, metadata)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         RETURNING *`,
        [escrowId, title, description, amount, requiredApprovals, nextIndex, JSON.stringify(metadata)]
    );
    const milestone = result.rows[0];

    if (onChain) {
        const contract        = await getContract();
        const bytes32Id       = uuidToBytes32(escrowId);
        const milestoneAmount = ethers.parseUnits(String(amount), 6);
        const tx              = await contract.createMilestone(
            bytes32Id,
            title,
            description || '',
            milestoneAmount,
            requiredApprovals
        );
        const receipt = await tx.wait();
        await pool.query(
            'UPDATE escrow_milestones SET tx_hash = $1 WHERE id = $2',
            [receipt.hash, milestone.id]
        );
        milestone.tx_hash = receipt.hash;
    }

    return milestone;
};

/**
 * Record a participant approval for a milestone.
 * Auto-advances the milestone to 'approved' and credits released_amount on the
 * parent escrow when the threshold is reached.
 *
 * @param {string} escrowId        UUID of multi_party_escrows
 * @param {number} milestoneId     Primary key of escrow_milestones
 * @param {{userId?:string, walletAddress:string, txHash?:string, blockNumber?:number}} opts
 * @returns {object} Updated escrow_milestones row
 */
const approveMilestone = async (
    escrowId,
    milestoneId,
    { userId = null, walletAddress, txHash = null, blockNumber = null }
) => {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        // Caller must be an active participant of the requested escrow.
        const participantRes = await client.query(
            `SELECT 1
             FROM escrow_participants
             WHERE escrow_id = $1
               AND LOWER(wallet_address) = LOWER($2)
               AND is_active = TRUE
             LIMIT 1`,
            [escrowId, walletAddress]
        );
        if (!participantRes.rows.length) {
            throw new Error(`Wallet ${walletAddress} is not a participant of escrow ${escrowId}`);
        }

        // Lock the milestone row
        const milestoneRes = await client.query(
            'SELECT * FROM escrow_milestones WHERE id = $1 AND escrow_id = $2 FOR UPDATE',
            [milestoneId, escrowId]
        );
        if (!milestoneRes.rows.length) {
            throw new Error(`Milestone ${milestoneId} not found for escrow ${escrowId}`);
        }
        const milestone = milestoneRes.rows[0];

        if (!['pending', 'in_progress'].includes(milestone.status)) {
            throw new Error(`Milestone ${milestoneId} is not in an approvable state (status: ${milestone.status})`);
        }

        // Insert approval – unique constraint prevents double-approval
        await client.query(
            `INSERT INTO milestone_approvals
                 (milestone_id, user_id, wallet_address, tx_hash, block_number)
             VALUES ($1, $2, $3, $4, $5)`,
            [milestoneId, userId, walletAddress, txHash, blockNumber]
        );

        // Compute new status
        const newCount  = milestone.approval_count + 1;
        const newStatus = newCount >= milestone.required_approvals ? 'approved' : 'in_progress';

        const updatedRes = await client.query(
            `UPDATE escrow_milestones
             SET approval_count = $1, status = $2, updated_at = NOW()
             WHERE id = $3
             RETURNING *`,
            [newCount, newStatus, milestoneId]
        );
        const updated = updatedRes.rows[0];

        // If just approved, credit released_amount on the escrow
        if (newStatus === 'approved') {
            await client.query(
                `UPDATE multi_party_escrows
                 SET released_amount = released_amount + $1,
                     status = CASE
                                  WHEN released_amount + $1 >= total_amount THEN 'released'
                                  ELSE status
                              END,
                     updated_at = NOW()
                 WHERE escrow_id = $2`,
                [milestone.amount, milestone.escrow_id]
            );
        }

        await client.query('COMMIT');
        logger.info(`Milestone ${milestoneId} approved by ${walletAddress}`);
        return updated;
    } catch (err) {
        await client.query('ROLLBACK');
        throw err;
    } finally {
        client.release();
    }
};

/**
 * Retrieve full escrow details including participants and milestones with their approvals.
 *
 * @param {string} escrowId UUID
 * @returns {object|null} Escrow record with nested milestones and participants, or null.
 */
const getEscrowDetails = async (escrowId) => {
    const escrowRes = await pool.query(
        'SELECT * FROM multi_party_escrows WHERE escrow_id = $1',
        [escrowId]
    );
    if (!escrowRes.rows.length) return null;
    const escrow = escrowRes.rows[0];

    const [milestonesRes, participantsRes] = await Promise.all([
        pool.query(
            `SELECT m.*,
                    COALESCE(
                        json_agg(
                            jsonb_build_object(
                                'wallet_address', a.wallet_address,
                                'user_id',        a.user_id,
                                'tx_hash',        a.tx_hash,
                                'approved_at',    a.approved_at
                            ) ORDER BY a.approved_at
                        ) FILTER (WHERE a.id IS NOT NULL),
                        '[]'::json
                    ) AS approvals
             FROM   escrow_milestones m
             LEFT   JOIN milestone_approvals a ON a.milestone_id = m.id
             WHERE  m.escrow_id = $1
             GROUP  BY m.id
             ORDER  BY m.order_index`,
            [escrowId]
        ),
        pool.query(
            'SELECT * FROM escrow_participants WHERE escrow_id = $1 ORDER BY joined_at',
            [escrowId]
        ),
    ]);

    return {
        ...escrow,
        milestones:   milestonesRes.rows,
        participants: participantsRes.rows,
    };
};

/**
 * List all multi-party escrows created by a user or linked to their invoices.
 *
 * @param {string} userId
 * @param {string} [status] Optional status filter
 * @returns {object[]}
 */
const listEscrowsByUser = async (userId, status = null) => {
    const params = [userId];
    let   where  = 'WHERE e.created_by = $1';
    if (status) {
        params.push(status);
        where += ` AND e.status = $${params.length}`;
    }

    const { rows } = await pool.query(
        `SELECT e.*,
                COUNT(DISTINCT m.id) AS milestone_count,
                COUNT(DISTINCT p.id) AS participant_count
         FROM   multi_party_escrows e
         LEFT   JOIN escrow_milestones   m ON m.escrow_id = e.escrow_id
         LEFT   JOIN escrow_participants p ON p.escrow_id = e.escrow_id
         ${where}
         GROUP  BY e.id
         ORDER  BY e.created_at DESC`,
        params
    );
    return rows;
};

module.exports = {
    createEscrow,
    activateOnChain,
    addParticipant,
    createMilestone,
    approveMilestone,
    getEscrowDetails,
    listEscrowsByUser,
};
